### ISSUE TITLE
Add possibility to relaunch pylint with different setting

### ISSUE THREAD

**Issue by StefanoFioravanzo** [AtomLinter/linter-pylint#107]
I would like to be able to toggle a specific flag of pylint on and off while working on a file without having to edit pylintrc file and relaunch atom.
More specifically, pylint has the 'py3k' option, which helps writing code compliant to python3. The problem is that while py3k is on, pylint won't give all the other usual warnings/errors. It would be great to have a toggle in atom to 'relaunch' pylint with this option on or off.

**Comment by Arcanemagus** [comment]
Pylint is executed fresh with every lint request, so every single lint is already a "relaunch".

The only way I can think of that is at all more convenient than just editing the configuration file is to add an option that toggles passing `--py3k` to `pylint`, and having a command that toggles that option (which can then be bound to a key binding if so desired).

A PR implementing this would be great to review, for now I'll leave this open so it will eventually be dealt with when somebody has some free time.

**Comment by Arcanemagus** [comment]
Was just thinking about this, and I'm really not seeing how a setting would be any different from editing your config file other than a _very_ slight convenience. You still would need to have the settings window open, switch to it, change the setting, then go back to the file you are working on to run a lint. This isn't really any different from having the configuration file open, commenting/uncommenting a line, saving, and switching back :confused:.

I'm going to mark this as closed, if you have a compelling reason that it should be implemented I'd be glad to hear it!
