### ISSUE TITLE
Do not undraw current lint issues unless they are fixed

### ISSUE THREAD

**Issue by bryson** [AtomLinter/linter-pylint#11]
Currently if I have a line highlighted yellow or red for a linter issue, every time I type a key the highlight disappears and reappears. 

The highlight should be drawn once, and then left in place until the linter signals that the issue it is highlighting was fixed, at which point it is removed.

**Comment by SpainTrain** [comment]
Looks like the upstream bug is closed.  Should this issue be closed?

**Comment by SpainTrain** [comment]
> Looks like the upstream bug is closed. Should this issue be closed?

I think yes :grin:
