### ISSUE TITLE
Command Line options not working in linter-pylint

### ISSUE THREAD

**Issue by ULTIMATEUPGRADE** [AtomLinter/linter-pylint#113]
I used the following as executable path for pylint 

/usr/local/bin/pylint –load-plugins=pylint_oca -d all -e odoolint

but it throws the following error message

Uncaught BufferedProcessError: Failed to spawn command `/usr/local/bin/pylint –load-plugins=pylint_oca -d all -e odoolint`. Make sure `/usr/local/bin/pylint –load-plugins=pylint_oca -d all -e odoolint` is installed and on your PATH

**Comment by Arcanemagus** [comment]
With the way spawning processes works you can't just enter arbitrary arguments into that setting, when it says "the path to `pylint`" it means that _and just that_. Arguments need to be pushed into the argument array before it is called [here](https://github.com/AtomLinter/linter-pylint/blob/v1.2.0/lib/main.coffee#L97).

If you want to put up a PR that allows customizable arguments I'm sure that would be welcome. Make sure that you filter out any user supplied arguments that would cause issues with how the linter works (ie. the predefined ones currently there).

**Comment by SpainTrain** [comment]
Note that you could also add these args to your pylintrc file (this is how I solved this problem).  You can do this per project or globally (http://docs.pylint.org/run.html#command-line-options)

**Comment by Arcanemagus** [comment]
Marking this as closed as these options can be specified in the configuration file.
