### ISSUE TITLE
Error: Problem importing module classes.py: cannot import name 'InferenceContext'

### ISSUE THREAD

**Issue by Yoshi325** [AtomLinter/linter-pylint#114]
I'm getting repeated errors like this:

```
Error: Problem importing module classes.py: cannot import name 'InferenceContext'
    at /Users/<UserName>/.atom/packages/linter-pylint/lib/main.coffee:99:23
```

I have uninstalled and reinstalled linter-pylint; the issue still persists.

My Atom version is 1.4.2 and my linter-pylint version is 1.2.0

**Comment by Arcanemagus** [comment]
Does `pylint` from the terminal work on the file from the file's directory?

**Comment by Yoshi325** [comment]
Nope. Looks like this might be an issue with pylint.

```
$ pylint .
Problem importing module classes.py: cannot import name 'InferenceContext'
************* 
F:  1, 0: error while code parsing: Unable to load file '__init__.py' ([Errno 2] No such file or directory: '__init__.py') (parse-error)
```

```
$ pylint --version
Problem importing module classes.py: cannot import name 'InferenceContext'
pylint 1.4.4, 
astroid 1.4.3, common 1.1.0
Python 3.4.4 (default, Jan 11 2016, 11:01:15) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

It would be nice if linter-pylint had some throttling on reporting these issues. It appears to keep trying to run pylint after every few keystrokes.

Also, I think this issue has been reported by others in: #116 and #117

**Comment by Yoshi325** [comment]
(Updating pylint fixed it for me.)

**Comment by Arcanemagus** [comment]
Actually those two issues are messages that `pylint` couldn't be found in the first place. Issue reporting is something that needs some work for sure, but isn't something that has been given much thought yet, if you have ideas anything would probably be handled in the `atom-linter` package :wink:.

Glad you got your issue figured out though!
