### ISSUE TITLE
Error: spawn pylint

### ISSUE THREAD

**Issue by jricobotella** [AtomLinter/linter-pylint#116]
Hi,

Everytime I open a ".py" file in Atom, appers the next error:

```
Error: spawn pylint ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

I'm using OS X El Capitan 10.11.3

Thanks in advance

**Comment by Arcanemagus** [comment]
Do you have `pylint` installed on your system?

**Comment by jricobotella** [comment]
Hi, Arcanemagus,

Yes pylint i'ts installed, see this:

$ pip install pylint
Requirement already satisfied (use --upgrade to upgrade): pylint in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): astroid<1.5.0,>=1.4.1 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from pylint)
Requirement already satisfied (use --upgrade to upgrade): colorama in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from pylint)
Requirement already satisfied (use --upgrade to upgrade): six in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from pylint)
Requirement already satisfied (use --upgrade to upgrade): lazy-object-proxy in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from astroid<1.5.0,>=1.4.1->pylint)
Requirement already satisfied (use --upgrade to upgrade): wrapt in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from astroid<1.5.0,>=1.4.1->pylint)

But the error remains.

TKS

**Comment by Arcanemagus** [comment]
If you run `which pylint`, and then put the output of that command into the Executable Path option, does it work for you?

**Comment by jricobotella** [comment]
Yes, it works correctly !!!! Many thanks.

I think the problem is that I have two versions of Python (Python2 and Python3) in my OS, and for some reason something was worg.

After running "which pylint" command in my computer and setting the output in the Executable Path, all is working fine.

Many thanks againg for your cooperation !!

**Comment by Arcanemagus** [comment]
Interesting, I wonder why the automatic path resolution wasn't working. In any case, I'm glad you got it working for you :wink:.

**Comment by rajivvishwa** [comment]
I'd the same issue on OSX 10.9 and I also had to set the executable path manually.

**Comment by steelbrain** [comment]
@rajivvishwa It's highly likely that you have a shell config that breaks the env extractor. If you have any prompts, make sure to only show them if stdout is a tty
