### ISSUE TITLE
Uncaught Error: spawn ENOENT

### ISSUE THREAD

**Issue by dengemann** [AtomLinter/linter-pylint#12]
it seems something is causing trouble with the recent Atom verions.

cf. https://github.com/atom/atom/issues/3091#issuecomment-50191902

cc @kevinsawicki

I meanwhile switched to https://atom.io/packages/linter-python-pep8 and https://atom.io/packages/linter-python-pyflakes

**Comment by lazamar** [comment]
I had the same error. The reason was I didn't have pylint installed.
On ubuntu just `sudo apt-get install pylint` solves the problem.
