### ISSUE TITLE
Add ignoring of specific codes

### ISSUE THREAD

**Issue by Asbra** [AtomLinter/linter-pylint#126]
Could you add support for ignoring specific codes from pylint?
Would be very smooth if they could be added by right-clicking in console, "Ignore this code"

**Comment by cblp** [comment]
Bad proposition. You should ignore them in your code.

**Comment by Arcanemagus** [comment]
Marking this as a duplicate of #113, you should be putting codes to ignore for a project in a configuration file that lives with the project.
