### ISSUE TITLE
Sort issues by severity

### ISSUE THREAD

**Issue by DanielJoyce** [AtomLinter/linter-pylint#128]
Currently issues are listed by line. It would be nice if they were sorted by severity as Pylint warns about code style stuff and actual bugs, so actual bugs should be at the top.

**Comment by Arcanemagus** [comment]
Messages aren't actually ordered at all currently, they are just presented in the order that they are given to us by `pylint`.

If you want the ability to sort issues by severity you should file this request on [linter-ui-default](https://github.com/AtomLinter/linter-ui-default).
