### ISSUE TITLE
Linter can't recoginze PyQt5

### ISSUE THREAD

**Issue by shiravand** [AtomLinter/linter-pylint#130]
As I said in the title linter can't recoginze PyQt module and it gives lots of warnings and error that are not true.
```python
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
```

```
Pylint  error  E0602 Undefined variable 'QMainWindow'at line 13 col 17
Pylint  error  E0602 Undefined variable 'pyqtSignal'at line 15 col 13
Pylint  error  E0602 Undefined variable 'QPushButton'at line 24 col 17
Pylint  error  E0602 Undefined variable 'QApplication'at line 37 col 6
```

**Comment by Arcanemagus** [comment]
Does `pylint` show the same messages when run from the CLI?

**Comment by shiravand** [comment]
Yes. It shows the same messages in the CLI.

**Comment by Arcanemagus** [comment]
This is an upstream issue in `pylint` then, you should file an issue on [their repo](https://github.com/PyCQA/pylint/) about this to get it fixed :wink:.
