### ISSUE TITLE
Pylama and Pylint warning

### ISSUE THREAD

**Issue by erdemalpkaya** [AtomLinter/linter-pylint#142]
<img width="1440" alt="screen shot 2016-05-05 at 11 04 20 am" src="https://cloud.githubusercontent.com/assets/18541694/15031978/31eb1540-12b1-11e6-9ced-2cec51edc13b.png">

I had this problem but Atom python was working before, then I downloaded python 3x version and I install - uninstall some of Atom packages I got this warning which when I open python folder it is displayed on my Atom interface

<img width="1440" alt="screen shot 2016-05-05 at 12 16 42 am" src="https://cloud.githubusercontent.com/assets/18541694/15032041/a2697cc6-12b1-11e6-9cd6-a991c82b56ec.png">

so I don't know what happen! Anyone knows?
I really need help I can't turn on python folder!

<img width="1440" alt="screen shot 2016-05-05 at 12 30 05 am" src="https://cloud.githubusercontent.com/assets/18541694/15032131/1fb762f6-12b2-11e6-9b36-c2dcd8821def.png">

**Comment by Arcanemagus** [comment]
What have you entered in your settings for the Executable path?

**Comment by erdemalpkaya** [comment]
Sorry but I know I created  the same issue but I don't know my problem is! I created two different packages! Anyway, I didn't enter anything in my Path just I install uninstall Atom packages then this happened. Do you know anything about it?

**Comment by Arcanemagus** [comment]
Hmmm, when you said "Atom python was working before" I assumed that you already had these packages installed before.

Do you have `pylint` and `pylama` installed on your system in the first place? Do they work from a terminal?

**Comment by erdemalpkaya** [comment]
OK! you can close this subject, I uninstall atom then I install again. I wish I knew the problem and fix it but no one knows. Anyway, thank you. Happy coding...

**Comment by Arcanemagus** [comment]
Glad to hear it's working for you!
