### ISSUE TITLE
configurate for a virtualenv

### ISSUE THREAD

**Issue by NicolasBB** [AtomLinter/linter-pylint#148]
Hi,

I've just started to use virtualenv on Windows and i have some problem Configurating my pylint in atom. What should I put in the settings?

my project folder look like this:
env
test.py

in env\
Include
Lib
Scripts
share

The python.exe is in Scripts and I use kivy as an import for testing. When using the python.exe manually and importing kivy it works so I'm sure the imports are correct.

I tried putting in Python Path
%p\env\Scripts\python.exe
%p\env\Scripts
%p\env
%p

What is the correct way of doing this on windows?

**Comment by Arcanemagus** [comment]
I would imagine you need something like `%p\env\Lib` in Python Path, and `%p\env\Scripts\python.exe` in the Executable Path.

**Comment by NicolasBB** [comment]
Thank you,
Actually I was been an idiot and I forgot to install pylint with pip in the virtualenv. Any way this is my config: %p\env\Lib in Python Path, and %p\env\Scripts\pylint.exe in the Executable Path.

**Comment by johnmoxon** [comment]
Had the same issue and thank you this resolved my issue too!
