### ISSUE TITLE
Please do not disable console.log

### ISSUE THREAD

**Issue by crucialfelix** [AtomLinter/linter-pylint#154]
It seems that this package is disabling console.log for everything in Atom. The message posted to the console (just before it does it) suggests that just Linter-Python will not post debug; but yet it is affecting all of us.

```
            console.log("[Linter-Python] Debug prints were disabled.");
            console.log = () => {};
```

It would be much better if you could change your implementation so that enableDebug just affects debugs posted from linter-python.

**Comment by Arcanemagus** [comment]
Looks like you need to file this over on [linter-python](https://github.com/pchomik/linter-python) 😉.

**Comment by crucialfelix** [comment]
Oh sorry !  I totally didn't notice that. Maybe I should switch back to this one anyway.
