### ISSUE TITLE
Example of using pylint in virtualenv

### ISSUE THREAD

**Issue by adamboche** [AtomLinter/linter-pylint#184]
After installing pylama-pylint (2.2.1) in my virtualenv, I didn't understand how to configure linter-pylint to use my virtualenv's pylint. Could there be an example of how to set this up in the documentation?

**Comment by jrial** [comment]
Currently it doesn't appear possible. By default (on Linux at least), virtualenvs are not stored near your project, but in $HOME/.virtualenvs instead. If you pick your project name to be the same as your virtualenv name, you could use a construct in the form of /home/my_user/.virtualenvs/$PROJECT_NAME/lib/python2.7/site_packages, but the variable $PROJECT_NAME is currently not understood by linter-pylint. See also #133

**Comment by talesa** [comment]
My slightly dirty workaround when using `virtualenvwrapper` on MacOS is to put `alias pylint='/usr/bin/env python $(which pylint)'` into my `.bash_profile`, and make sure you have `pylint` installed in each of your environments by putting `pip3 install pylint` into `$VIRTUALENVWRAPPER_HOOK_DIR/postmkvirtualenv`.

**Comment by ddaanet** [comment]
@adamboche To use your virtualenv pylint with linter-pylint, set the "Executable Path" in the package settings to point to bin/pylint in your virtualenv.

There are more complicated configurations, and various solutions, but now I am only answering your question.

Atom `linter-pylint` has no use for Python `pylama-pylint`. `pylama-pylint` lets Python `pylama` use `pylint`. To integrate `pylama` with Atom `Linter`, you need to use the Atom `linter-pylama` package.
