### ISSUE TITLE
cannot import name warn

### ISSUE THREAD

**Issue by morenoh149** [AtomLinter/linter-pylint#192]
I get the following error

```
Error: Traceback (most recent call last): File "/Users/harry/programming/pharmakon/env/pharmakon/bin/pylint", line 11, in
sys.exit(run_pylint()) File "/Users/harry/programming/pharmakon/env/pharmakon/lib/python2.7/site-packages/pylint/init.py", line 22, in
run_pylint from pylint.lint import Run File "/Users/harry/programming/pharmakon/env/pharmakon/lib/python2.7/site-packages/pylint/lint.py",
line 31, in import contextlib File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 5, in
from warnings import warn ImportError: cannot import name warn
```

pylint is available on my path as I can execute it in the terminal just fine. What might be the problem?

**Comment by Arcanemagus** [comment]
That error isn't anything that _could_ be thrown from this package or Atom, it _looks_ like it's being forwarded on from `pylint` itself.

From looking at the code, it seems this package attempts to workaround the common issue with most of the Python related linters in that they don't support `stdin` input, so currently it is creating a temporary file  and linting that. This causes major issues with imports which _might_ be what you are hitting here. Are you able to provide the file/project you are seeing this on to attempt to reproduce and verify this guess?

**Comment by morenoh149** [comment]
no sadly it's closed source. If I notice the problem on another project I'll follow up here.

**Comment by Arcanemagus** [comment]
Closing this as unable to reproduce, if you are still seeing this some code to test with would be great 😉.
