### ISSUE TITLE
Warning on "TODO" comment

### ISSUE THREAD

**Issue by Olian04** [AtomLinter/linter-pylint#193]
This row: `#TODO: stuff`
Produces this warning: `[Pylint] [warning] W0511 TODO: stuff at line 33 col 1`

**Comment by Arcanemagus** [comment]
The message is coming from pylint, if you want to disable it simply do so in your `.pylintrc` file.

**Comment by Olian04** [comment]
@Arcanemagus i know its coming from pylint.. but why is it trowing a `warning` on a comment? If anything this should be a `convention` not a `warning`. And why is it reacting to the term "TODO" anyways? It doesn't react to "todo" lowercased..

Also, please open this up again. It shouldn't be closed.

**Comment by Arcanemagus** [comment]
@Olian04 this has _nothing_ to do with this package, so I'm leaving this closed. If you feel that the current behavior of `pylint` isn't correct you should file an issue [over there](https://github.com/PyCQA/pylint/issues) so the people that can actually do something about it can take a look at it 😉.

For example, the fact that it reacts to `TODO` and not `todo` I would consider to be a bug, but it might have been done intentionally as most people use `TODO` to delineate it from using "todo" in comments.
