### ISSUE TITLE
[BUG] Linting shown as editor errors instead of Gutter notations!

### ISSUE THREAD

**Issue by Thelete** [AtomLinter/linter-pylint#194]
As shown in the image, common errors; such as `AttributeError: 'int' object has no attribute 'typ'` are falsely being displayed as editor errors instead of linter Gutter notations.

![](http://i.imgur.com/qANYU0B.png)

**Comment by Arcanemagus** [comment]
That looks like a crash of `pylint` itself actually, what happens if you save the file immediately when seeing that, and then run `pylint` from the CLI?

**Comment by Arcanemagus** [comment]
CLosing due to a lack of response. If you are able to reproduce this please try running `pylint` in the CLI to see if it works there!
