### ISSUE TITLE
Error while loading pylint

### ISSUE THREAD

**Issue by igalbakal** [AtomLinter/linter-pylint#195]
After installing pylint with linter as a dependency in Atom editor:
Every time I open a .py file, I get the follwing error:
```
Error: spawn pylint ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Arcanemagus** [comment]
Do you have `pylint` installed? Is it on your `$PATH`?

**Comment by igalbakal** [comment]
It is installed as an atom extension.

**Comment by Arcanemagus** [comment]
This package is simply a translator between running `pylint` on the CLI and the Linter Atom package. This means that you need to be able to run `pylint` on the CLI for this to work at all.

**Comment by austinbutler** [comment]
Ran into this today. I think I had to upgrade or reinstall pylint because Homebrew upgraded me to Python 3.6.

Try running `pylint` via command line and see if it fails.

I got this for example:
`zsh: /usr/local/bin/pylint: bad interpreter: /usr/local/opt/python3/bin/python3.5: no such file or directory`

**Comment by mrpbennett** [comment]
I am running into the same thing also, I have also installed python via homebrew

**Comment by igalbakal** [comment]
OK, it works now.
installed pylint (on mac os terminal: sudo pip/pip3 install pylint) 
enabled extention in Atom and it works.

Thank you.

**Comment by gitanupam** [comment]
@igalbakal @Arcanemagus I have installed pylint from terminal but still get the same error on Atom:

```
Error: spawn pylint ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any thoughts?

**Comment by gitanupam** [comment]
FYI: Got it working by following the suggestion [here](https://github.com/AtomLinter/linter-ruby/issues/80#issuecomment-244625389)  (I'm not using Ruby though).

Ran `which pylint` and pasted the output in the field 'Executable Path' under the linter package's 'Settings' in Atom.

**Comment by LisaDSJones** [comment]
please help me here @gitanupam. Where did you run which pylint? I have the same error as you. When i run in my terminal `which pylint` absolutely nothing happens: no error or any other output.

**Comment by Arcanemagus** [comment]
> When i run in my terminal which pylint absolutely nothing happens: no error or any other output.

@LisaDSJones this means that your system doesn't know where `pylint` exists. Either you don't have it installed at all, or wherever you have it installed is not on your `$PATH`. If you _do_ have it installed either add that location to your `$PATH`, or enter the _full_ path (eg. `/usr/local/bin/pylint`) in the settings for Executable Path.

**Comment by gitanupam** [comment]
@LisaDSJones Did you install pylint when your virtualenv was activated? I did that and so `which pylint` results in `/Users/Anupam/ENV/bin/pylint` (where ENV is my virtualenv) only when my virtualenv is activated. If you installed pylint in your virtualenv and it is not activated now, then `which pylint` may return nothing.

**Comment by LisaDSJones** [comment]
@Arcanemagus I do have it installed, but I don't know where. How do i find where it's installed?

@gitanupam I don't know what virtualenv is.

**Comment by Arcanemagus** [comment]
@LisaDSJones `which pylint` _is_ how you find where it is installed... assuming it was installed properly. How did you install it?

**Comment by LisaDSJones** [comment]
@Arcanemagus I'm pretty new to atom, but I went to settings/install and in the search bar i searched for linter-py and pushed the install button

**Comment by Arcanemagus** [comment]
This package is just a wrapper around running `pylint` from your system. As the [installation](https://github.com/AtomLinter/linter-pylint#installation) section of the README says the first step is installing `pylint` 😉.

You can find basic installation instructions for `pylint` over on [their site](https://www.pylint.org/#install).
