### ISSUE TITLE
import error when using linter-pylint

### ISSUE THREAD

**Issue by EDWhyte** [AtomLinter/linter-pylint#197]
I obtain the following error message when I attempt to use linter-pylint

Error: Problem importing module imports.py: No module named 'isort'
    at file:///C:/Users/username/.atom/packages/linter-pylint/lib/main.js:130:19
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by EDWhyte** [comment]
I am using an Anaconda distribution of python3 and install pylint using the conda install command. Anaconda does not have a isort distribution and therefor it was not installed. 

Solution:
You can either install isort using pip
or
install pylint using pip in which case isort will be install alongside pylint

**Comment by bilderbuchi** [comment]
I ran into the same thing, reported at ContinuumIO/anaconda-issues#1383.
