### ISSUE TITLE
Choose to Ignore Some linter errors

### ISSUE THREAD

**Issue by ThomasAntoniusCrowley** [AtomLinter/linter-pylint#223]

**Comment by smadamson** [comment]
I would like to know how to ignore the line length warning. If anyone knows how I can do this, please share.

**Comment by Arcanemagus** [comment]
You should look at the [`pylint` documentation](https://pylint.readthedocs.io/en/latest/user_guide/run.html) for how to do that, this package is merely a wrapper around that.
