### ISSUE TITLE
Linting on temporary files means imports don't work

### ISSUE THREAD

**Issue by dmnd** [AtomLinter/linter-pylint#23]
You can get around this problem by adding a `pylintrc` file, though it's annoying to do for every project:

```
[MASTER]
init-hook='sys.path.insert(0, '.')'
```

I suspect this wouldn't be necessary if we linted actual files instead of temporary ones.

I think using temporary files for linter is problematic. Maybe we should stop doing that, and drop support for lint on change.

**Comment by SpainTrain** [comment]
I believe that #55 fixes this issue.  Please feel free to test and validate this is true.

**Comment by SpainTrain** [comment]
Should be closed in the latest release (sans relative imports, see https://github.com/AtomLinter/linter-pylint/issues/58).  @dmnd mind closing this if this is true?

**Comment by steelbrain** [comment]
@SpainTrain can you contact me in #atom of atom slack please?
