### ISSUE TITLE
Marks accesses from imported .so file as error

### ISSUE THREAD

**Issue by Cazra** [AtomLinter/linter-pylint#234]
I'm working on some Python code that imports a .so file to do some of its work. The code works fine and the import itself isn't flagged as an error, but linter-pylint always marks any functions or members called from it as an error. I've got the directory containing the .so file in my $PYTHONPATH too.

**Comment by ddaanet** [comment]
That look like a problem with pylint. There are various options in pylint to handle such issues. Here I guess you want to set the `extension-pkg-whitelist` option.

Please only report here issues that apply to the integration of pylint with atom using the `linter-pylint` package. Any issue that occurs with pylint without `linter-pylint` should reported to pylint.
