### ISSUE TITLE
How is it meant to work?

### ISSUE THREAD

**Issue by tobiasfielitz** [AtomLinter/linter-pylint#239]
Installed it via atom - settings - install, doesn't do anything afterwards. Can type whatever I like in my .py files - nothing. Have restarted atom - nothing. I've set the absolute path to pylint (runs properly on command line) in the settings and left all other settings as default. Still nothing.

```
Atom 1.23.1
pylint 2.1.0
```

**Comment by ddaanet** [comment]
Did you install the `linter` atom package?

**Comment by tobiasfielitz** [comment]
`linter 2.2.0` is installed too, yes
![screen shot 2018-01-12 at 10 21 42 am](https://user-images.githubusercontent.com/9712861/34852374-6afc8cd0-f782-11e7-9b92-f80c86d1bd03.png)

**Comment by ddaanet** [comment]
There's not much we can do with what you gave us.

If linter and linter-pylint are installed in Atom, pylint is installed on your system, and the linter-pylint configuration points the pylint executable, it should at least display some error notification. Maybe look for output in the developer console.

Did you check linter-pylint is not in the "disabled providers" config of linter?

**Comment by Arcanemagus** [comment]
@tobiasfielitz Can you open a file that you are expecting messages on and run `Linter: Debug` from the Command Palette?

**Comment by tobiasfielitz** [comment]
![screen shot 2018-01-19 at 9 32 43 am](https://user-images.githubusercontent.com/9712861/35124881-c1fc1144-fcfb-11e7-9ff7-76e0bef2780d.png)

That looks good to me.

@ddaanet "disabled providers" is empty.

**Comment by Arcanemagus** [comment]
You have no UI installed (enabled?). Install `linter-ui-default` to get an interface for you to see something 😉.

**Comment by tobiasfielitz** [comment]
Sweet @Arcanemagus !! That was it. It was disabled. Don't know why, didn't even know I had/needed `linter-ui-default`. Thanks heaps guys for looking into this, much appreciated!! :-)
