### ISSUE TITLE
linting requires rcfile

### ISSUE THREAD

**Issue by Talon24** [AtomLinter/linter-pylint#251]
When a path to a pylintrc-file is specified, e.g. `%f\.pylintrc`, it will always expect that file to be present in the relative location, otherwise it will fail with 
`raise IOError("The config file {:s} doesn't exist!".format(config_file))`. 
But as I edit files outside of my default code folder where there is no rcfile, it might be useful to have a fallback-logic if the file is not present in that file's folder, something like 
```
Does this file exist? 
    Yes: Run pylint with it. 
    No:  Run pylint using default settings
```

**Comment by Arcanemagus** [comment]
Sounds like a pretty simple PR if you want to take a stab at it 😉.
