### ISSUE TITLE
linter-pylint borked

### ISSUE THREAD

**Issue by acgetchell** [AtomLinter/linter-pylint#26]
Here's what I get when I open a python file in Atom 0.172.0 with linter-pylint 0.2.0:

![screen shot 2015-01-13 at 9 52 51 pm](https://cloud.githubusercontent.com/assets/434849/5734733/8580fea0-9b6f-11e4-9323-b43adfcf680f.png)

When I disable linter-pylint the issue goes away.

**Comment by dmnd** [comment]
See #150. You need to make sure `pylint` is on your PATH, and that you
launch Atom from the command line so it inherits the PATH.

**Comment by acgetchell** [comment]
I didn't have this issue with Atom 0.169.0 and earlier versions of pylon.

**Comment by dmnd** [comment]
:+1:
