### ISSUE TITLE
How to disable/enable errors/warnings/info messages in Atom?

### ISSUE THREAD

**Issue by vinisalazar** [AtomLinter/linter-pylint#262]
I have been trying to remove info messages (ticked in blue) and even warning messages (ticked in yellow). I did my share of Googling and trying to figure it out by myself but I couldn't do it.

I tried running:
`pylint --disable=W`

to disable warnings for instance, but to no avail. Any suggestions? Thank you.

**Comment by LeptoSpira** [comment]
you change your `.pylintrc` file to include `disable=W` under `[MESSAGES CONTROL]`

**Comment by Arcanemagus** [comment]
You can control what information is displayed in the UI you are using, or you can control what results `pylint` generates in the first place using it's configuration as suggested above.
