### ISSUE TITLE
Doesn't show error for imports of packages not installed

### ISSUE THREAD

**Issue by kumarmsingh** [AtomLinter/linter-pylint#265]
PyCharm detects & shows an error, if package is not installed, but imported. Pylint on Atom doesn't show error for imports of packages which are not installed.

**Comment by Arcanemagus** [comment]
You should file this as an enhancement request for `pylint` or use something like [ide-python](https://atom.io/packages/ide-python), which is far more likely to support something like that.

In either case this package is just a wrapper around `pylint`, so it shouldn't be filed here 😉.
