### ISSUE TITLE
Show linter codes

### ISSUE THREAD

**Issue by bmhkim** [AtomLinter/linter-pylint#28]
I'd really like to see the linter code included with the linter message. An example use case involves working on a codebase that's not entirely PEP-8 compliant. (e.g. tabs instead of spaces) Display of the pylint code makes it easier to disable the message in the project's .pylintrc.

**Comment by posita** [comment]
Please include the human readable versions as well (e.g., `unused-argument` is synonymous with [`W0613`](http://pylint-messages.wikidot.com/messages:w0613), etc.).

**Comment by bmhkim** [comment]
I've got a fix for this hacked together, and will submit a pull request.

**Comment by bmhkim** [comment]
@posita If you want this immediately, I have a fork that seems to be working for me: [bmhkim/linter-pylint](https://github.com/bmhkim/linter-pylint)

**Comment by posita** [comment]
Nice! :+1:

**Comment by SpainTrain** [comment]
:+1:

**Comment by SpainTrain** [comment]
This should be closed in the latest released version.  @bmhkim mind confirming and closing if true?

**Comment by posita** [comment]
LGTM:

![screen shot 2015-08-31 at 08 39 48](https://cloud.githubusercontent.com/assets/222581/9582727/e3d76f9c-4fbb-11e5-9519-b2dce91521ca.png)

**Comment by SpainTrain** [comment]
@posita are those import errors true positives?  There is an issue open for false positives on relative imports (https://github.com/AtomLinter/linter-pylint/issues/58).

Thanks for testing!

**Comment by posita** [comment]
> @posita are those import errors true positives?

They are valid(ish). They are absolute imports provided via a `virtualenv` that Atom is not aware of, so I'm pretty sure they are not implicated in #58.

**Comment by SpainTrain** [comment]
Awesome, just wanted to make sure =-D

Thanks!
