### ISSUE TITLE
Syntax errors do not tell you the collumn

### ISSUE THREAD

**Issue by LeptoSpira** [AtomLinter/linter-pylint#286]
This is pretty easy of a fix I believe, when there is a syntax error in my code, Black tells me where, including the column, while pylint just has `<unknown>` as the column number
##### **Black:**
![image](https://user-images.githubusercontent.com/47790183/57563810-6f28ff80-7370-11e9-9412-29cfa59d824e.png)
##### **Pylint:**
![image](https://user-images.githubusercontent.com/47790183/57563813-7e0fb200-7370-11e9-9501-b06ea03322d7.png)

**Comment by Arcanemagus** [comment]
This looks like an issue with `pylint` itself, this is just a wrapper around that that brings the results into the Atom editor. You should report this to [Pylint](https://github.com/PyCQA/pylint).
