### ISSUE TITLE
False errors with openCV

### ISSUE THREAD

**Issue by majk-p** [AtomLinter/linter-pylint#44]
I'm using openCV in my code. I'm working on OSX 10.10.4 (Yosemite). I've installed openCV via brew so I only have cv2.so file. After importing the openCV into my project i get errors like  `Module 'cv2' has no 'VideoCapture' member at line...` .
![lintererror](https://cloud.githubusercontent.com/assets/7260594/8451202/af2938e8-1fe1-11e5-9b64-bef4f378815e.png)
In fact, openCV has such a method and the code works. The reason is there's no header file or so, making linter not able to detect methods.

**Comment by SpainTrain** [comment]
@majk-p If you run pylint from the command line, do you get the same error?  If so, I believe this is an upstream issue with `pylint` itself.  See https://bitbucket.org/logilab/pylint/issues/58 

> We can't get sane behaviour for C based libraries all the time.

**Comment by SpainTrain** [comment]
@majk-p I forgot to mention, there is a workaround for this issue.  I had the same problem with dynamically exported members in a library I was using, so I wrote https://gist.github.com/SpainTrain/b5d4689156f0190700ef .  See the links in the gist's comment for more background on why this approach works.

**Comment by SpainTrain** [comment]
I am going to close this for now as I think it's an upstream issue.  Please reopen if you find that behavior is different in the plugin than on the CLI.

**Comment by NullYing** [comment]
I get the same quesition in the vscode

**Comment by crazyquark** [comment]
I have the same issue

**Comment by Arcanemagus** [comment]
@NullYing This is a package for Atom, not VSCode. Please find the appropriate repository for whatever plugin you are using.

@crazyquark As stated in the issue above, this is an upstream issue and there is nothing that can be done about it here.
