### ISSUE TITLE
Per project .pylintrc file configuration

### ISSUE THREAD

**Issue by s0undt3ch** [AtomLinter/linter-pylint#45]
Each project that I work on has 2 `.pylintrc` files, `.pylintrc` and `.testing.pylintrc`, the later is used for CI linting though I sometimes use that one for linting while typing.
Currently I seem to only be able to either choose one or the other, globally.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-pylint/pull/55
