### ISSUE TITLE
Not all errors are show!?

### ISSUE THREAD

**Issue by s0undt3ch** [AtomLinter/linter-pylint#46]
Here's what my atom shows:
![atom-pylint](https://cloud.githubusercontent.com/assets/300048/8504133/65aab442-21c3-11e5-9018-5b826aff0064.png)

Here's the console output with the same executable and pylintrc file:
![atom-pylint-1](https://cloud.githubusercontent.com/assets/300048/8504125/2450a65a-21c3-11e5-8cbc-9fde15cd1fad.png)

Is there some kind of logging where we can see what's going on?

**Comment by SpainTrain** [comment]
I seem to be observing something similar.  E.g., `undefined-variable` violation is reported by CLI but not by `linter-pylint` in atom.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-pylint/pull/55
