### ISSUE TITLE
Linter-PyLint not working in Atom 1.0 on Mac

### ISSUE THREAD

**Issue by radu-sover** [AtomLinter/linter-pylint#48]
Lint-Pylint is not analyzing the files in the Atom 1.0 on the mac Yosemite osx.
The plugin works fine under Windows with atom 1.0.
PyLint is installed on the mac. from the terminal i can run pylint and i get the analysis results.

Linter-flake8 seems to work on the mac with atom 1.0

If more info is needed please let me know.

**Comment by SpainTrain** [comment]
:+1: This appears to be the case in Linux also.  Same deal, pylint works on CLI and other linters (e.g., linter-pep8) work.

Infos:

```
$ uname -a
Linux myhostname 3.16.0-43-generic #58-Ubuntu SMP Fri Jun 19 11:04:02 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.10
DISTRIB_CODENAME=utopic
DISTRIB_DESCRIPTION="Ubuntu 14.10"
```

**Comment by arielpontes** [comment]
Exact same problem here.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-pylint/pull/55
