### ISSUE TITLE
Object.activate is deprecated.

### ISSUE THREAD

**Issue by s0undt3ch** [AtomLinter/linter-pylint#49]
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
Object.activate (/home/vampas/.atom/packages/linter/lib/main.coffee:57:8)
Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
<unknown> (/usr/share/atom/resources/app.asar/src/package.js:221:30)
Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
```

**Comment by jaskinn** [comment]
+1

**Comment by vitalibertas** [comment]
+1

**Comment by jaympatel** [comment]
+1

**Comment by JonnyCBB** [comment]
+1

**Comment by wdan** [comment]
+1

**Comment by snkisuke** [comment]
+1

**Comment by bilderbuchi** [comment]
:+1:

**Comment by llann** [comment]
+1

**Comment by kikelosada** [comment]
+1

**Comment by osscca** [comment]
+1

**Comment by ghostlurker** [comment]
+1

**Comment by SpainTrain** [comment]
:+1:

**Comment by fvm** [comment]
+1 (![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png))

**Comment by developEdwin** [comment]
+1

**Comment by JohnPHogan** [comment]
+1

**Comment by jadatkins** [comment]
I'm not sure the "+1"s are really helping. You can subscribe to the issue without spamming everybody. If you all all care so much, fix it yourself. We're obviously all coders here, and I'm sure CoffeeScript can't be that hard to learn.

**Comment by webberpuma** [comment]
+1

**Comment by bilderbuchi** [comment]
without the +1s there's no way for the devs to judge user interest/impact of the bug, as the number of subscriptions is not publicly visible, afaik. with +1s, you at least get the number of participants in the lower right.

**Comment by mekhanique** [comment]
Additionally,  there are folks who are contractually restricted from contributing to OSS as well part of their employment. How else do they make their need known to the community?

**Comment by kankaristo** [comment]
I agree that the +1s are important to the devs, but I also find them annoying (as a user, not a dev). I'm subscribed to a lot of issues, and get a dozen "+1" emails every day.

I wish GitHub added voting on issues. That would let the developers know how many people are affected by a bug, but subscribers wouldn't get notifications. I made a Gmail filter which automatically archives "+1" replies, but it doesn't catch ":+1:" or "+1, I really want this too"...

And now I'm likely to annoy a bunch of subscribers by spamming their inboxes and being completely off-topic. Sorry. :P

**Comment by SpainTrain** [comment]
Recommend further discussion of github social norms and issue voting be moved to existing issues for those things such as

https://github.com/isaacs/github/issues/9

https://github.com/isaacs/github/issues/209

**Comment by kebertx** [comment]
:+1:, I've been pretty eager to see the deprecation issues fixed, the linter hasn't been working for me since atom 1.0.3, and I've been back in emacs for my python work ever since.

Sorry for spamming you more, @kankaristo - I hope you're having a lovely day and that my :+1:ing doesn't get you down!

**Comment by kankaristo** [comment]
@kebertx, it doesn't when there's an intelligent comment attached to the :+1: ;)

I've been using [linter-flake8](https://atom.io/packages/linter-flake8), but less lint (and more linters) is always better.

**Comment by JohnPHogan** [comment]
It seems that my +1 comment was sort of the tipping point for the feedback about how it wasn't necessarily appropriate to do that.  If offence was taken, I apologise.  

In my current environment, any PEP-8 violation will cause my code to be rejected, and, as noted, atom is not very forgiving of packages with depreciations since the 1.x upgrade.  I do appreciate the work done to create and maintain the package and also appreciate the suggestion of linter-flake8.

Cheers

**Comment by SpainTrain** [comment]
Here's a PR https://github.com/AtomLinter/linter-pylint/pull/55 that updates to the new API; it should clear up this issue.  I tried to keep feature and behavior parity while following the latest atom linter patterns and conventions.  **Would love for some folks to test it out and shake out any bugs.**  If you are unfamiliar with installing dev packages from PRs, there are instructions in the PR description.  Thanks!

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-pylint/pull/55

**Comment by SpainTrain** [comment]
While I hate to spam a closed thread, given the lively discussion about +1's :wink: I figured several folks would be interested in contributing to this public appeal to GitHub on this issue - https://www.change.org/p/github-inc-add-voting-functionality-for-github-issues
