### ISSUE TITLE
LinterPylint.Linter is deprecated.

### ISSUE THREAD

**Issue by s0undt3ch** [AtomLinter/linter-pylint#50]
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
LinterPylint.Linter (/home/vampas/.atom/packages/linter/lib/linter.coffee:60:4)
new LinterPylint (/home/vampas/.atom/packages/linter-pylint/lib/linter-pylint.coffee:16:4)
Object.lint (/home/vampas/.atom/packages/linter/lib/legacy.coffee:61:21)
<unknown> (/home/vampas/.atom/packages/linter/lib/editor-linter.coffee:68:23)
<unknown> (/home/vampas/.atom/packages/linter/lib/editor-linter.coffee:67:24)
Set.forEach (native)
```

**Comment by JonnyCBB** [comment]
+1

**Comment by wdan** [comment]
+1

**Comment by bondgeek** [comment]
+1, guessing this is an AtomLinter problem, not a linter-pylint issue.

**Comment by bilderbuchi** [comment]
+1

**Comment by JohnPHogan** [comment]
+1

**Comment by rbsolis** [comment]
+1

**Comment by ma0dvl** [comment]
Using code from other Atom linter packages, which use linter, I were able to write a pylint based linter which is compatible with the new API. Here is the link: https://github.com/ma0dvl/linter-advpylinter
I had no experience with CoffeeScript, so it would be good if someone would check the code. Maybe a pull request for this repository can be done using my draft.

**Comment by SpainTrain** [comment]
Here's a PR https://github.com/AtomLinter/linter-pylint/pull/55 that updates to the new API; it should clear up this issue.  I tried to keep feature and behavior parity while following the latest atom linter patterns and conventions.  **Would love for some folks to test it out and shake out any bugs.**  If you are unfamiliar with installing dev packages from PRs, there are instructions in the PR description.  Thanks!

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-pylint/pull/55
