### ISSUE TITLE
LinterFlake8.Linter is deprecated.

### ISSUE THREAD

**Issue by kikelosada** [AtomLinter/linter-pylint#51]
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API     LinterPylint.Linter  /home/enrique/.atom/packages/linter/lib/linter.coffee:60:4  new LinterPylint  /home/enrique/.atom/packages/linter-pylint/lib/linter-pylint.coffee:16:4  Object.lint  /home/enrique/.atom/packages/linter/lib/legacy.coffee:61:21  unknown>  /home/enrique/.atom/packages/linter/lib/editor-linter.coffee:69:25  currentLinter  /home/enrique/.atom/packages/linter/lib/editor-linter.coffee:68:19  unknown>  /home/enrique/.atom/packages/linter/lib/editor-linter.coffee:82:22

**Comment by SpainTrain** [comment]
Here's a PR https://github.com/AtomLinter/linter-pylint/pull/55 that updates to the new API; it should clear up this issue.  I tried to keep feature and behavior parity while following the latest atom linter patterns and conventions.  **Would love for some folks to test it out and shake out any bugs.**  If you are unfamiliar with installing dev packages from PRs, there are instructions in the PR description.  Thanks!

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-pylint/pull/55
