### ISSUE TITLE
linter-pylint Deprecated: Atom 1.0.3 OS X 10.10.4

### ISSUE THREAD

**Issue by A-M-R** [AtomLinter/linter-pylint#52]
<img width="1029" alt="screen shot 2015-07-29 at 10 12 50 pm" src="https://cloud.githubusercontent.com/assets/13447051/8974388/3ba6001c-363f-11e5-960d-324ffefde6b8.png">
Also deprecated under Atom 1.0.2. 

All packages are updated, checked both within Atom and using `apm outdated`

linter 1.2.4 installed

**Comment by matalo33** [comment]
This breaks linter-pylint with [atom-community/linter](https://github.com/atom-community/linter) > [1.2.4](https://github.com/atom-community/linter/tree/v1.2.4) as they deprecated the API.

To fix linter-pylint in the meantime before a fix is available downgrade the linter package with the following:

`apm install linter@1.2.4`

**Comment by A-M-R** [comment]
@matalo33 Thank you for the response!

**Comment by SpainTrain** [comment]
Here's a PR https://github.com/AtomLinter/linter-pylint/pull/55 that updates to the new API; it should clear up this issue.  I tried to keep feature and behavior parity while following the latest atom linter patterns and conventions.  **Would love for some folks to test it out and shake out any bugs.**  If you are unfamiliar with installing dev packages from PRs, there are instructions in the PR description.  Thanks!
