### ISSUE TITLE
Issue with On-The-Fly linting

### ISSUE THREAD

**Issue by beefybug** [AtomLinter/linter-pylint#54]
There seems to be an issue with linting on the fly when using the zip version of Atom in windows. When lint on the fly is enabled, no linting is done. The same issue exist for linter-pylama as well. When I disable on the fly for linter-pylama, it works. I have a feeling that it is due to the fact that in a "portable" version of Atom, the temp file is not visible for on the fly linting.

However, there is no option to disable lint on the fly for linter-pylint. Disabling the option in the main linter package did not resolve this issue.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-pylint/pull/55
