### ISSUE TITLE
Errors without a positional element are difficult to view

### ISSUE THREAD

**Issue by meatbody** [AtomLinter/linter-pylint#66]
Errors with a specific positional element, such as "line too long" errors, produce an underlined section that exposes the error text when the cursor is placed within it at the location of the error (I have "Underline Issues" checked in my linter settings). However, errors without a positional component, such as a "has no member" error, do not produce this underline and the only way to expose the error is to search through the "Error Panel" at the bottom of the Atom window. For example:

![screen shot 2015-09-02 at 1 28 04 pm](https://cloud.githubusercontent.com/assets/391741/9777578/fad68f50-571a-11e5-89cc-3416f0eac0ef.png)

In the above image, the error is "E1101 Instance of has no 'model' member". I'd expect to see an underlined section on the given line (perhaps where 'model' is referenced), or to have the inline error tooltip show up when I click anywhere on the line.

Atom 1.0.10
linter 1.5.0
linter-pylint 1.0.0
linter-pep8 1.0.1
one-dark-syntax 1.1.0
one-dark-ui 1.0.3

(reposted from atom-community/linter#875)

**Comment by SpainTrain** [comment]
doh!  The 0 col errors should highlight the whole line.

Can you do me a favor and share the output of pylint when run from the CLI (that is, the error as output from pylint on your machine)?  Also, just for context, what's your OS?

**Comment by meatbody** [comment]
I'm on OSX Yosemite, 10.10.3.

$ pylint --version
pylint 1.2.1,
astroid 1.1.1, common 0.61.0
Python 2.7.9 (default, Feb 10 2015, 03:28:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]

For the two "convention" lines in the screenshot above:

C:273, 4: Missing method docstring (missing-docstring)
C:274, 8: Invalid variable name "pk" (invalid-name)

For the two "error" lines:

E:278,22: Instance of 'CommonBaseAdsAdmin' has no 'model' member (no-member)
E:279,19: Instance of 'CommonBaseAdsAdmin' has no 'model' member (no-member)

I found I can actually get the inline error tooltip to show up on the error lines (not the convention lines though) by placing my cursor in the space to the right of the '=' sign on the first line and in the space after 'except' in the second line. However, there's no error underline on these positions to indicate this.

![screen shot 2015-09-10 at 9 54 23 am](https://cloud.githubusercontent.com/assets/391741/9794808/09d56314-57a2-11e5-8fdf-a1c881ce8bbb.png)

**Comment by steelbrain** [comment]
@SpainTrain the decorations need at least one character between them to be able to show something, so if something starts at char `2` and ends at char `2`, inline bubbles would work but underlining would not

**Comment by SpainTrain** [comment]
That's right, it handles the 0-0 col case but not other single columns. 

I can take a look at improving this.

**Comment by Arcanemagus** [comment]
I think this issue was filed before this project moved to using `rangeFromLineNumber()` to generate the ranges, as such I'm marking this as closed. If the upcoming v1.3.0 (or v2.0.0) release is still not working for this then please file a new issue with a Python file that reproduces the problematic ranges.
