### ISSUE TITLE
Donate button image 403

### ISSUE THREAD

**Issue by miigotu** [AtomLinter/linter-pylint#68]
https://chewbacco-stuff.s3.amazonaws.com/donate.png is 403 with this xml now:

```xml
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>0CC96D46FCD758CE</RequestId>
<HostId>
DzDgqNQZLgAeN0aS6YLIsZoEdEmqS9jx9BoQKBK0tpTIbsFvmz/0TmRXlv06fzHy
</HostId>
</Error>
```

**Comment by steelbrain** [comment]
We could review a PR that removes it from the docs.

**Comment by miigotu** [comment]
I'd be glad to, but I'm not sure what the old image looked like, or what the new one ~should~ look like.

**Comment by steelbrain** [comment]
You can just drop the whole section

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-pylint/pull/69
