### ISSUE TITLE
PyLint console does not contain any web hyperlinks + unable to copy/paste

### ISSUE THREAD

**Issue by ssbarnea** [AtomLinter/linter-pylint#77]
As an user I was expecting to be able to click on a PyLint message in order to get more information about what was wrong and what should I do to fix it.

Now the only links are towards the code where the problem occurs.

I do expect to be able to click something (probably the message key, like C0103) and to open the default browser with a page with more details.

Probably this page should be google search on pytlint+keycode

**Comment by SpainTrain** [comment]
This is a cool idea.  It requires support from `linter`.

@steelbrain is there a plan to allow links in the error panel?

**Comment by steelbrain** [comment]
We've already added this feature to latest linter, you can select the bottom panel text. Due to some unidentified complications, it hasn't been done in inline bubble yet.

**Comment by steelbrain** [comment]
Nevermind, I mis-read it. @SpainTrain You can specify html elements as well as raw html to the linter as messages, so you can easily implement them in this provider.

**Comment by SpainTrain** [comment]
Oh awesome.  Thanks for the info.  Might someday have bandwidth to implement, but setting this as `help wanted` as I will happily review a PR anytime!

Thanks for the suggestion @ssbarnea
