### ISSUE TITLE
Linter cannot find pylint

### ISSUE THREAD

**Issue by TheGuardianWolf** [AtomLinter/linter-pylint#80]
Am running windows, Pylint was added via pip.

However this error is occurring:
```
Failed to spawn command pylint. Make sure pylint is installed and on your PATH

Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
  at exports._errnoException (util.js:814:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  at onErrorNT (internal/child_process.js:344:16)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)
```

I have checked and pylint does run in cmd so it does happen to be on the PATH. I've tried manually setting it but that still does not work.

**Comment by SpainTrain** [comment]
Can you share you `config.cson`?  This shouldn't be an issue in windows, but could you try running atom from CLI and see if the issue persists?

**Comment by Aeon-Firebrand** [comment]
Tried running from CLI, seems to be working now.

Went back and tested atom from just normal launch, that's working too.

I did reinstall pylint but not sure if that would affect anything as previously I've tried doing that with no success.

But anyway, issue is solved now.

**Comment by tildebyte** [comment]
@SpainTrain : I have exactly same issue, only it's not auto-resolving for me. I have:
* Win 7 Pro, atom 1.2.4, all plugins up-to-date
* Win 10 Pro, atom 1.2.4, all plugins up-to-date

Both machines:
* Have up-to-date Anaconda Python 2.7, with `flake8`, `pylint`, and `autopep8` `conda install`ed
* Can run all three commands from command prompt without issue

Here's my [`config.cson`](https://gist.github.com/tildebyte/f69343b922d72af59069), but consider this: `flake8` and `autopep8` work *without configuration* (`autopep8` isn't a `linter` plugin, but it's similar enough to `flake8` and `pylint` to provide another data point).
`linter-pylint` has worked on both machines before (as recently as yesterday).
Running atom from shortcut/directly from batch/from command line/as admin/not as admin - none of that makes any difference.

**--version:**
`flake8`: 2.3.0 (pep8: 1.6.2, pyflakes: 1.0.0, mccabe: 0.3)
`pylint`: pylint-script.py 1.4.2, astroid 1.3.4, common 0.63.2
`autopep8`: autopep8 1.2.1

**atom errors:**
Pop-up
````js
Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
````

Console
`Uncaught BufferedProcessError: Failed to spawn command pylint. Make sure pylint is installed and on your PATH C:\Users\______\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:260`

**Comment by Arcanemagus** [comment]
Silly question, but does `C:\WINDOWS\system32\cmd.exe` exist?

**Comment by tildebyte** [comment]
Not **that** silly, but yes.

**Comment by Aeon-Firebrand** [comment]
I had to do a clonezilla restore today on the computer that was affected by this issue previously, so I thought I'd provide some additional info. It is working perfectly here on the first try unlike last time.

Atom was preinstalled with the image.
I installed linter package, then the pylint package for linter.
I added python's script folder to path, then ran 'pip install pylint'.

After these steps, it immediately started working without errors.

**Comment by tildebyte** [comment]
Another weird data point which I forgot last night: tracing file i/o with Sysinternals `procmon` shows (or perhaps, doesn't show) that atom isn't even *looking* for the `pylint` executable, and that it *is* finding the Python scripts directory with no problem.

**Comment by Arcanemagus** [comment]
@tildebyte Does it work if you hard code the path in the config?

**Comment by SpainTrain** [comment]
@tildebyte odd.  Could you open dev tools in atom (same hotkey as chrome), set a breakpoint inside linter-pylint, and see whether the plugin is being run?

**Comment by tildebyte** [comment]
@Arcanemagus I've tried putting all *sorts* of things in the config, including the path to `pep8` just for kicks.

@SpainTrain I'll try to do that sometime this evening.

**Comment by Arcanemagus** [comment]
Just to be specific: On my system at least the `executablePath` setting would be `C:\Python27\Scripts\pylint.exe` if I were to hard code it.

**Comment by tildebyte** [comment]
Really should be `C:/Python27/Scripts/pylint.exe` (note the slashes).
FYI, `linter-pylama` is working fine here, and I think I'm going to stick with it, as it works well, and includes, like, *everything* (McCabe, PEP257, PEP8, PyFlakes, Pylint).

**Comment by Arcanemagus** [comment]
The slashes were correct, although either _should_ work.

**Comment by Yarn** [comment]
I'm having this issue. Placing a breakpoint at line 73 or 76 in main.coffee seems to indicate the add-on is being run.
Also at line 83 of helper.js after an exception was thrown I looked at the value of _ref in case it helps
![capture](https://cloud.githubusercontent.com/assets/908816/11765306/f7f8924e-a105-11e5-9551-a255b8b43ab0.PNG)

**Comment by wangjoshuah** [comment]
any update on this for mac? I've got pylint working from terminal, but get "Failed to spawn command pylint. Make sure pylint is installed and on your PATH" and 
`Error: spawn pylint ENOENT
Error: spawn pylint ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)`
error as well.

**Comment by Saberre** [comment]
I had a same issue and found that when a file is opened as directory (like below screenshot) 'cwd' value has a path to file, not a directory.

![image](https://cloud.githubusercontent.com/assets/458539/13481849/31b2de2a-e12c-11e5-969b-a8d84d8630ba.png)

If you can debug pylint script, set a breakpoint in line 76 of main.coffee and check what `cwd` variable has.

**Comment by fx86** [comment]
pylint throws the same error on OSX as above. 

@wangjoshuah  Did you get something to work ?

**Comment by Arcanemagus** [comment]
Marking this as closed, if you are still experiencing this please file a _new_ issue with details such as:

* Operating system
* Atom version
* Whether `pylint` is working from the CLI for you
* How you are launching Atom
