### ISSUE TITLE
Linter produces yellow marks in editor, but error/warning popup will not show

### ISSUE THREAD

**Issue by DanielJoyce** [AtomLinter/linter-pylint#82]
Sometimes I get a yellow marker in the gutter showing a warning is available, but no amount of hovering or clicking will cause the popup or tooltip to appear. There is also dashed line to show where the error is at.

**Comment by SpainTrain** [comment]
Can you share your `config.cson`?

**Comment by brevilo** [comment]
Same here with vanilla setup (v1.2.0)...
The relevant part of `config.cson` just has `"linter-pylint": {}`

**Comment by Arcanemagus** [comment]
Have you disabled tooltips in Linter's configuration?

Also Linter only decorates with _dashed_ lines, so I'm not sure what the "yellow-dotted lines" would be from. A screenshot would be helpful there.

Where is your cursor directed when you click on the "at line __ col ___" part of the message?

**Comment by brevilo** [comment]
I do get tooltips for dashed lines (see above) and all linter packages have their upstream/stock settings.

Here's a screenshot:
  
![2016-01-22 01 37 34 pm](https://cloud.githubusercontent.com/assets/985598/12510922/c3023662-c10d-11e5-949d-7d40a40f7012.png)

Interestingly it seems as if these warnings aren't even listed in the error panel...

**Comment by Arcanemagus** [comment]
Is the column 0 by any chance? :stuck_out_tongue:

**Comment by brevilo** [comment]
No, it's not, but I think I found the problem:

When I place the cursor manually at the exact column that's given in the error panel the tooltip pops up. If I place the cursor anywhere else on the affected line it doesn't. However, sometimes the marked column isn't even "accessible" due to indentation so the tooltip will never show up. Anyhow, the tooltip should appear as soon as the cursor is placed anywhere on a marked line, or, better yet, by hovering with mouse over the line (anywhere) or over the gutter marker.

**Comment by DanielJoyce** [comment]
This is exactly what I see. Hints that I can't get tooltips or mouseovers
for. In general at very least atom needs to support tooltips for the little
dots even if the squiggles don't show. So this may be partly an atom bug as
well.

On Fri, Jan 22, 2016 at 10:10 AM Oliver Bock <notifications@github.com>
wrote:

> No, it's not, but I think I found the problem:
>
> When I place the cursor manually at the exact column that's given in the
> error panel the tooltip pops up. If I place the cursor anywhere else on the
> affected line it doesn't. However, sometimes the marked column isn't even
> "accessible" due to indentation so the tooltip will never show up. Anyhow,
> the tooltip should appear as soon as the cursor is placed anywhere on a
> marked line, or, better yet, by hovering with mouse over the line
> (anywhere) or over the gutter marker.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AtomLinter/linter-pylint/issues/82#issuecomment-173996490>
> .
>
-- 
Daniel Joyce

The meek shall inherit the Earth, for the brave will be among the stars.

**Comment by Arcanemagus** [comment]
So here is the odd thing: This _should_ be generating highlight ranges that cover the line starting with the column that `pylint` specifies, which is a decent compromise between "all errors highlighting the entire line" and "only a single character where the linter says".

Do you have an example file you can share that shows the "dot with no line" behavior so we can look into it a bit further in detail?

In the meantime you can enable the "Line" mode in the settings for Linter, then the bottom panel will show you all messages for the currently selected line.

**Comment by brevilo** [comment]
> Do you have an example file you can share that shows the "dot with no line" behavior

Sure, just cause an "Unused variable" warning (only works within functions for some reason):
```
def test():
    x = 1
```
This should also demonstrate the off-by-one issue which might cause the issue in the first place: x is at column 5 but the error panel reports column 4. Thus you can't put the cursor on the spot when auto-indent is enabled (see above).

**Comment by sneakypete81** [comment]
@Arcanemagus: any progress? I see the same issue with the simple test provided by @brevilo above.

This problem crops up quite often.

**Comment by Arcanemagus** [comment]
@sneakypete81 tl;dr CoffeeScript is terrible and [this mess](https://github.com/AtomLinter/linter-pylint/blob/v1.2.0/lib/main.coffee#L104) wasn't doing whatever the original author thought it was doing.

On the good news, I've re-written this in ES6 and it seems to work fine so far 😛. I'll be putting that up in a PR shortly.

**Comment by sneakypete81** [comment]
Great to hear, thanks!

**Comment by sneakypete81** [comment]
@arcanemagus: Really pleased that you've fixed this. It would be great to have a release pushed out with this fix.

The last release was >6 months ago. Now that your rewrite is done, I'm sure shorter release cycles would be much appreciated by your many users.

**Comment by Arcanemagus** [comment]
Hmmm, not sure why I didn't push out a release before, will look into that now. Thanks for the ping on getting that out 😉.

**Comment by Arcanemagus** [comment]
v1.2.1 published, please file an issue if you see any issues!

**Comment by sneakypete81** [comment]
@Arcanemagus: thanks heaps, that release works beautifully.
