### ISSUE TITLE
Support file-local environment variables in pylint setting (and others)

### ISSUE THREAD

**Issue by alyssa-kwan-cloverhealth** [AtomLinter/linter-pylint#84]
To accommodate workflows using such tools as ``pyenv``, support file-local environment variables.

``pyenv`` has a ``pyenv local`` command, which writes a ``.python-version`` file. Shelling into that directory, assuming ``pyenv`` is properly enabled in the ``.profile`` setup, leads to that specific Python being loaded. In conjunction with ``pyenv-virtualenv``, virtualenvs are supported that get loaded into a ``$VIRTUAL_ENV`` variable.

(Sorry for the explanation. Saw in a different issue here on GitHub the statement that the Python ecosystem has no ``.ruby-version``. It, in fact, does.)

Given that, you can obviously set up workspaces. And each Python source file can be tied to a specific ``$VIRTUAL_ENV/bin/pylint`` and ``$PYTHONPATH``. Given that, it'd be nice to use these, assuming that ``pylint`` is launched per file.

I'm willing to submit a PR, if someone will validate that this is even possible.

**Comment by alyssackwan** [comment]
Damn it, that's my work GitHub. Contact me here if direct contact needed.

**Comment by SpainTrain** [comment]
Would love a PR for this.

It seems possible.  As long as you end up with an absolute path (or command that exists in the `PATH` var that atom has), the command will work.  If you want to draw it out in a bit more detail before creating the PR, I am happy to further validate its potential to work.

**Comment by SpainTrain** [comment]
related https://github.com/AtomLinter/linter-pylint/issues/75

**Comment by Arcanemagus** [comment]
Marking this as closed, I _think_ the `PYTHONPATH` and `executable` path expansion available covers this, if not please re-open and clarify the issue a bit.
