### ISSUE TITLE
PYTHONPATH does not work

### ISSUE THREAD

**Issue by trunneml** [AtomLinter/linter-pylint#86]
All imports showing pylint errors. The problem seems to be that the PYTHONPATH environment variable is not set on my system when pylint is executed. I replaced pylint with a shell script that pushes all env vars in a text file but PYTHONPATH was not in that text file.

I also added some console.error lines in linter-pylint to show the env var object, which shows an attribute called PYTHONPATH with the right parameters.

├── linter@1.10.0
├── linter-pylint@1.0.3

Any Ideas?

**Comment by SpainTrain** [comment]
Can you test this with the latest version and reopen if not fixed?  thanks
