### ISSUE TITLE
Add support for arbitrary pylint arguments

### ISSUE THREAD

**Issue by hanks42** [AtomLinter/linter-pylint#92]
I'd like to send pylint arguments like disabling certain messages and changing the max line length. There should be a way to send arbitrary arguments into pylint when it runs. For example to send these arguments I had to edit the plugin source

--max-line-length=100 -d I0011,C0303

**Comment by SpainTrain** [comment]
Thanks for the enhancement suggestion.

Does using an rcfile for this not fit your use case?

**Comment by hanks42** [comment]
Ah yes it does actually thanks! I saw the rcfile option but wasn't familiar with it's purpose.

**Comment by SpainTrain** [comment]
Great!  I will leave this open as "PR welcome" in case someone does end up with a use case for this.

**Comment by Arcanemagus** [comment]
Marking this as a duplicate of #113 since it contains a bit more information.
