### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by DStewart1997** [AtomLinter/linter-pylint#94]
Getting this weird error constantly while editing my code - it happened after reinstalling pylint to try and get it to accept python 3 code.

Python Version: Python 3.4.3
Pylint Version: pylint 1.4.4, 
Astroid: astroid 1.3.8, common 1.1.0

I've had a look at the __init__.py and main.coffee but can't figure it out.
```
Error: Exception ignored in: > Traceback (most recent call last): File "/usr/lib/python3.4/site-packages/enchant/init.py", line 244, in del File "/usr/lib/python3.4/site-packages/enchant/init.py", line 273, in _free TypeError: 'NoneType' object is not callable
Error: Exception ignored in: <bound method Broker.__del__ of <enchant.Broker object at 0x7f8236dc6ba8>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/enchant/__init__.py", line 244, in __del__
  File "/usr/lib/python3.4/site-packages/enchant/__init__.py", line 273, in _free
TypeError: 'NoneType' object is not callable
    at /home/dstewart/.atom/packages/linter-pylint/lib/main.coffee:84:23

**Comment by Arcanemagus** [comment]
Does `pylint` work from the command line? This looks like an internal error in that, which is beyond what this package deals with. We just pass on the messages it gives :wink:.

**Comment by DStewart1997** [comment]
Never thought of trying that but yeah, looks like it's working fine from command line. So looks like the issue is with linter-pylint then, yeah?

**Comment by DStewart1997** [comment]
Looks like I was wrong, re-ran and now I get the error: 

Global evaluation
-----------------
Your code has been rated at 8.84/10 (previous run: 6.14/10, +2.70)

```Exception ignored in: <bound method Broker.__del__ of <enchant.Broker object at 0x7f2ceabedd30>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/enchant/__init__.py", line 244, in __del__
  File "/usr/lib/python3.4/site-packages/enchant/__init__.py", line 273, in _free
TypeError: 'NoneType' object is not callable```

Looks like it is a PyLint issue, sorry about that. Thanks.

**Comment by Arcanemagus** [comment]
No worries, glad we could narrow it down a little bit :wink:.
