### ISSUE TITLE
ENOENT error when opening Atom

### ISSUE THREAD

**Issue by MihaiVisu** [AtomLinter/linter-pylint#99]
I get ENOENT error for linter-pylint after opening Atom. I have pylint installed though.

**Comment by Arcanemagus** [comment]
This usually means that it either can't find it automatically, or the path you have configured isn't valid. Can you try putting the full path (including the `pylint` part!) to `pylint` in the configuration?

**Comment by MihaiVisu** [comment]
Yes, I had to configure my custom path in my PC. Previous versions were able to find it automatically.

**Comment by Arcanemagus** [comment]
What OS are you on? How were you launching Atom?

**Comment by MihaiVisu** [comment]
OS X El Capitan. I installed Atom through the dmg file and was launching it normally.
